### ISSUE TITLE
Failed to Run

### ISSUE THREAD

**Issue by ihebski** [YSc21/webcocktail#1]
`$ python3 webcocktail.py 
Traceback (most recent call last):
  File "webcocktail.py", line 6, in <module>
    from webcocktail.webcocktail import WebCocktail
  File "/home/ubuntu/Desktop/webcocktail/webcocktail/webcocktail.py", line 16, in <module>
    from webcocktail.scanner import Scanner
  File "/home/ubuntu/Desktop/webcocktail/webcocktail/scanner.py", line 1, in <module>
    import plugins
  File "/home/ubuntu/Desktop/webcocktail/plugins/__init__.py", line 15, in <module>
    module = importlib.util.module_from_spec(spec)
AttributeError: 'module' object has no attribute 'module_from_spec'
`

**Comment by YSc21** [comment]
I'm not sure why you get this bug. Maybe you should upgrade your python3. Thanks.

**Comment by ihebski** [comment]
Hey @YSc21 Thanks a lot for your answer, it works fine with Python 3.9.8.
2017 -> 2021 that's quite a long time xD
